### Data
The dataset utilized in this research comprises two CSV files detailing the ingredients and pastries for a bakery's production planning. The first file, ingredients.csv, lists the quantities of three key ingredients available: 57.5 units of yeast, 112.5 units of flour, and 245 units of sugar. The second file, pastry.csv, provides detailed information about three types of pastries: Apple Pie, Croissant, and Poppy Seed. For each pastry, the dataset includes its name, price, and the quantities of yeast, flour, and sugar required for production. Specifically, the Apple Pie requires 0.75 units of flour and 1.5 units of sugar; the Croissant needs 0.5 units of yeast, 1.5 units of flour, and 0.25 units of sugar; and the Poppy Seed demands 1.15 units of yeast, 1.5 units of flour, and 0.75 units of sugar. This dataset provides a comprehensive basis for optimizing production strategies to maximize profit within the given ingredient constraints.

In [82]:
import pandas as pd
ingredients = pd.read_csv("ingredients.csv")
print(ingredients)
print(ingredients.columns)

   Yeast  Flour  Sugar
0   57.5  112.5    245
Index(['Yeast', 'Flour', 'Sugar'], dtype='object')


In [83]:
data = pd.read_csv("pastry.csv")
print(data)
print(data.columns)

          Name  Price  Yeast  Flour  Sugar
0   Apple Pie    2.99   0.00   0.75   1.50
1   Croissant    2.50   0.50   1.50   0.25
2  Poppy Seed    5.99   1.15   1.50   0.75
Index(['Name', 'Price', 'Yeast', 'Flour', 'Sugar'], dtype='object')


## Profit Maximization 

### Method 
To determine the optimal production quantities of pastries for maximizing profit, we employed linear programming techniques. First, the availability of ingredients (yeast, flour, and sugar) was defined based on the data from the ingredients.csv file. We then extracted the price and ingredient requirements for each pastry from the pastry.csv file. The objective function, aimed at maximizing profit, was represented by the negative prices of the pastries. The inequality constraints were constructed to ensure the total usage of each ingredient did not exceed the available quantities, with additional constraints to prevent negative production values. We formulated the problem as a linear program and solved it using the linprog function from the SciPy library. The results provided the optimal quantities of each pastry to produce, thereby maximizing the overall profit.

In [84]:
import pandas as pd
import numpy as np
from scipy.optimize import linprog

# The constraints of how many ingredients are available 
yeast_available = ingredients["Yeast"].values
flour_available = ingredients["Flour"].values
sugar_available = ingredients["Sugar"].values

In [85]:
data = pd.read_csv("pastries.csv")
prices = -data["Price"].values  
# The code below seperates the pastries with respect to the ingredients   
yeast_requirements = data["Yeast"].values
flour_requirements = data["Flour"].values
sugar_requirements = data["Sugar"].values

In [86]:
# The inequality constraints (A_ub * x <= b_ub)
# A_ub has the requirements of each of the ingredients to make the three pastries 
A_ub = np.array([yeast_requirements, flour_requirements, sugar_requirements,[-1,0,0],[0,-1,0],[0,0,-1]])
# b_ub has the requirements of each of the available ingredients to make the three pastries 
b_ub = np.concatenate((yeast_available, flour_available, sugar_available, [0, 0, 0]))

In [87]:
# Solving the linear programming problem
answer = linprog(prices, A_ub=A_ub, b_ub=b_ub)

In [88]:
# Extract results
max_profit = -answer.fun
pastry_quantities = answer.x

In [89]:
# Output the results
print(f"The max profit is {max_profit:.2f} and can be achieved by producing:")
for i, pastry in enumerate(data["Name"]):
    quantity = pastry_quantities[i]
    print(f"* {pastry}: {quantity:.2f} pieces")


The max profit is 449.00 and can be achieved by producing:
* Apple Pie : 50.00 pieces
* Croissant : 0.00 pieces
* Poppy Seed : 50.00 pieces


### Output
The optimization results indicate that the maximum profit achievable with the available ingredients is $449.00. To reach this profit, the optimal production strategy involves making 50 pieces of Apple Pie and 50 pieces of Poppy Seed, while not producing any Croissants. This allocation fully utilizes the available ingredients—57.5 units of yeast, 112.5 units of flour, and 245 units of sugar—ensuring no resources are wasted. The decision to prioritize Apple Pie and Poppy Seed over Croissants is driven by the goal of maximizing profit, given the ingredient constraints and the selling prices of the pastries.